#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

#--------------------------------------------------
# service links for cupsd
#--------------------------------------------------
$service = "cups";

service_link_enhanced($service, "S90", "7");

#--------------------------------------------------
# actions for network-create event
#--------------------------------------------------

$event = "network-create";

templates2events("/etc/cups/cupsd.conf", $event);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/cups");

#--------------------------------------------------
# actions for network-delete event
#--------------------------------------------------

$event = "network-delete";

templates2events("/etc/cups/cupsd.conf", $event);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/cups");

#--------------------------------------------------
# actions for bootstrap-console-save event
#--------------------------------------------------

$event = "bootstrap-console-save";

templates2events("/etc/logrotate.d/cups", $event);
templates2events("/etc/cups/mime.convs", $event);
templates2events("/etc/cups/mime.types", $event);
templates2events("/etc/cups/cupsd.conf", $event);

#--------------------------------------------------
# actions for console-save event
#--------------------------------------------------

$event = "console-save";

templates2events("/etc/cups/cupsd.conf", $event);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/cups");

#--------------------------------------------------
# actions for cups-update event
#--------------------------------------------------

$event = "nethserver-cups-update";

templates2events("/etc/cups/mime.convs", $event);
templates2events("/etc/cups/mime.types", $event);
templates2events("/etc/cups/cupsd.conf", $event);
templates2events("/etc/samba/smb.conf", $event);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/cups");
safe_symlink("reload", "root/etc/e-smith/events/$event/services2adjust/smbd");

# Make ppds accessible via samba

safe_symlink("/etc/cups/ppd", "root/home/e-smith/files/primary/files/cups-ppds");

# Link for web interface

safe_symlink("/etc/e-smith/web/panels/manager/cgi-bin/printers", "../../../functions/printers");
