#!/usr/bin/perl -wT

#----------------------------------------------------------------------
# heading     : Configuration
# description : Printers
# navigation  : 6000 6400
# 
# Copyright (C) 2003,2005 Robert van den Aker <robert2@dds.nl>
# This script uses functions that are copyright (C) 2002 Mitel Networks
# Corp.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 		
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 		
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
# USA.
# 
#----------------------------------------------------------------------

use strict;
use esmith::FormMagick::Panel::cups;

my $panel = esmith::FormMagick::Panel::cups->new();
$panel->display();

__DATA__
<form title="FORM_TITLE" header="/etc/e-smith/web/common/head.tmpl" 
footer="/etc/e-smith/web/common/foot.tmpl">

  <page name="Initial" pre-event="turn_off_buttons()"
    post-event="printer_sync()">
    <subroutine src="show_initial()"/>
  </page>
  <page name="Status" pre-event="print_status_message()">
  </page>

</form>
