#!/usr/bin/perl -wT

#----------------------------------------------------------------------
# heading     : Configuration
# description : Printers
# navigation  : 6000 6400
#
# copyright (C) 2002 Mitel Networks Corp.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
#
#----------------------------------------------------------------------

use strict;
use esmith::FormMagick::Panel::printers;

my $fm = esmith::FormMagick::Panel::printers->new();
$fm->display();

__DATA__
<form title="FORM_TITLE" header="/etc/e-smith/web/common/head.tmpl"
    footer="/etc/e-smith/web/common/foot.tmpl">
    <page name="First" pre-event="print_status_message">
        <description>INITIAL_DESC</description>
        <subroutine src="show_printers()"/>
        <subroutine src="cups_gui()"/>
    </page>

    <page name="Delete" pre-event="turn_off_buttons">
    </page>

    <page name="ConfirmDelete" pre-event="turn_off_buttons"
        post-event="delete_printer">
        <title>REMOVE_PRINTER</title>
        <subroutine src="show_delete_confirmation()"/>
        <subroutine src="print_button('REMOVE')"/>
    </page>

</form>
