#!/bin/sh

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

event=$1
sourceDir=$2
dbFile="/home/e-smith/db/configuration"
printersFile="/etc/cups/printers.conf"
classesFile="/etc/cups/classes.conf"

if [ ! -d $sourceDir ] || [ "x$sourceDir" == "x" ]; then
    echo "Could not find dir: $sourceDir";
    exit 1
fi

mkdir -p /etc/cups/
cp  -p "$sourceDir/$printersFile" $printersFile
cp  -p "$sourceDir/$classesFile" $classesFile

status=`/sbin/e-smith/db $sourceDir/$dbFile getprop cups status`
/sbin/e-smith/config setprop cups status $status

/sbin/e-smith/signal-event nethserver-cups-update
